### ISSUE TITLE
Specify number of inputs when creating component

### ISSUE THREAD

**Issue by KierranM** [meringu/circuits#7]
When you create a new component it creates the default number of inputs, 2 for an AND gate for example. This is a nice default, but currently if you want to create an AND gate that has more than two inputs you must pre-create them and pass them in like so:
```ruby
and_gate = Circuits::Component::And.new inputs: (1..4).map { Circuits::Terminal::Input.new }
```

It would be better if you could instead specify a number of inputs that the gate should have like so:
```ruby
and_gate = Circuits::Component::And.new num_inputs: 4
```

**Comment by KierranM** [comment]
The `:inputs` parameter could even be re-used here, with a check for whether it is an `Array` or `FixNum`

**Comment by meringu** [comment]
:+1:
